version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - frontend_network

networks:
  frontend_network:
